name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            aws ecr get-login-password --region eu-west-1 | sudo docker login --username AWS --password-stdin 658606186312.dkr.ecr.eu-west-1.amazonaws.com &&
            sudo docker pull 658606186312.dkr.ecr.eu-west-1.amazonaws.com/my-python-app:latest &&
            sudo docker rm -f my-python-app || true
            sudo docker run -d --name my-python-app -p 8000:8000 658606186312.dkr.ecr.eu-west-1.amazonaws.com/my-python-app:latest
          "
